HQ_API = {
    "host": "10.255.255.1",
    "port": 8728,
    "user": "ClaudeMCP",
    "password": "Flvby_106QazWsx2",
}

WAZUH = {
    "host": "172.16.16.100",
    "port": 55000,
    "user": "wazuh",
    "password": "Wazuh.2026-Luch",
}

UNIFI = {
    "host": "172.16.16.5",
    "port": 8443,
    "user": "Luch74",
    "password": "5mB1woO6SaTn",
}

BRANCHES = [
    {"id": 25,  "name": "ekb_novostroya",           "city": "Екатеринбург"},
    {"id": 26,  "name": "serov",                     "city": "Серов"},
    {"id": 27,  "name": "Ekb-New-Sklad-Shevrof",     "city": "Екатеринбург"},
    {"id": 30,  "name": "tobolsk_franchiz",           "city": "Тобольск"},
    {"id": 31,  "name": "rezh_franchiz",              "city": "Реж"},
    {"id": 50,  "name": "orsk_franchiz",              "city": "Орск"},
    {"id": 61,  "name": "sibay",                      "city": "Сибай"},
    {"id": 63,  "name": "chtz",                       "city": "Челябинск"},
    {"id": 99,  "name": "Chelsi",                     "city": "Челябинск"},
    {"id": 105, "name": "nignevartovsk",              "city": "Нижневартовск"},
    {"id": 106, "name": "Kartaly-call-2",             "city": "Карталы"},
    {"id": 107, "name": "asbest",                     "city": "Асбест"},
    {"id": 110, "name": "Ekb_Donbas",                "city": "Екатеринбург"},
    {"id": 111, "name": "Luch-Cargo-001",             "city": "Челябинск"},
    {"id": 116, "name": "Neftekamsk",                "city": "Нефтекамск"},
    {"id": 117, "name": "Nefteugansk",               "city": "Нефтеюганск"},
    {"id": 121, "name": "branch-121",                "city": "—"},
    {"id": 130, "name": "hanty",                     "city": "Ханты-Мансийск"},
    {"id": 137, "name": "troitsk",                   "city": "Троицк"},
    {"id": 141, "name": "Perm_Franchiz-1",           "city": "Пермь"},
    {"id": 151, "name": "kartaly_franshiz",          "city": "Карталы"},
    {"id": 152, "name": "miass2",                    "city": "Миасс"},
    {"id": 153, "name": "Naberegnie_Chelny_Franchiz","city": "Набережные Челны"},
    {"id": 154, "name": "tagil_franchiz",            "city": "Нижний Тагил"},
    {"id": 157, "name": "Asha_Franchiz",             "city": "Аша"},
    {"id": 164, "name": "Uchaly-Franschiz",          "city": "Учалы"},
    {"id": 165, "name": "ufa5",                      "city": "Уфа"},
    {"id": 174, "name": "kyshtym_franchiz",          "city": "Кыштым"},
    {"id": 175, "name": "ufa4",                      "city": "Уфа"},
    {"id": 177, "name": "ufa6",                      "city": "Уфа"},
    {"id": 182, "name": "garage",                    "city": "Челябинск"},
    {"id": 187, "name": "kurgan_nekrasovo",          "city": "Курган"},
    {"id": 189, "name": "U-KATAV_FRANCHIZ",          "city": "Усть-Катав"},
    {"id": 190, "name": "berezniki_franchiz",        "city": "Березники"},
    {"id": 192, "name": "Sterlitamak-Franchiz",      "city": "Стерлитамак"},
    {"id": 193, "name": "ekb_office-2",              "city": "Екатеринбург"},
    {"id": 194, "name": "Korkino-Franchiz",          "city": "Коркино"},
    {"id": 195, "name": "trexgornii",                "city": "Трёхгорный"},
    {"id": 199, "name": "mechaniki_luch",            "city": "Челябинск"},
    {"id": 202, "name": "perm_franchiz-2",           "city": "Пермь"},
    {"id": 204, "name": "chel-moldavsk",             "city": "Челябинск"},
    {"id": 205, "name": "Astana-1",                  "city": "Астана",       "country": "KZ"},
    {"id": 207, "name": "ufa",                       "city": "Уфа"},
    {"id": 209, "name": "kostanai2",                 "city": "Костанай",     "country": "KZ"},
    {"id": 210, "name": "garage2-luch",              "city": "Челябинск"},
    {"id": 212, "name": "zlatoust",                  "city": "Златоуст"},
    {"id": 216, "name": "uznouralsk",                "city": "Южноуральск"},
    {"id": 221, "name": "Chebarkul-Sklad",           "city": "Чебаркуль"},
    {"id": 222, "name": "tumen",                     "city": "Тюмень"},
    {"id": 223, "name": "Ekb-New-Sklad",             "city": "Екатеринбург"},
    {"id": 225, "name": "Vufalei_Franchiz",          "city": "Верхний Уфалей"},
    {"id": 226, "name": "Izhevsk_Franchiz",          "city": "Ижевск"},
    {"id": 227, "name": "chusovoi",                  "city": "Чусовой"},
    {"id": 229, "name": "sneginsk",                  "city": "Снежинск"},
    {"id": 232, "name": "kopeisk",                   "city": "Копейск"},
    {"id": 233, "name": "beloreck_franchiz",         "city": "Белорецк"},
    {"id": 235, "name": "kuralsk_franchiz",          "city": "Кваркено"},
    {"id": 237, "name": "uruzan",                    "city": "Юрюзань"},
    {"id": 238, "name": "Eshim-Sklad",               "city": "Ишим"},
    {"id": 239, "name": "Noyabrsk",                  "city": "Ноябрьск"},
    {"id": 240, "name": "orenburg_franchiz",         "city": "Оренбург"},
    {"id": 241, "name": "Pervouralsk_Franchiz",      "city": "Первоуральск"},
    {"id": 242, "name": "chel-dovatora",             "city": "Челябинск"},
    {"id": 243, "name": "satka",                     "city": "Сатка"},
    {"id": 244, "name": "Samara",                    "city": "Самара"},
    {"id": 246, "name": "magnitogorsk",              "city": "Магнитогорск"},
    {"id": 247, "name": "shadrinsk",                 "city": "Шадринск"},
    {"id": 248, "name": "New-Urengoy-1",             "city": "Новый Уренгой"},
    {"id": 250, "name": "Almaty-KZ",                 "city": "Алматы",       "country": "KZ"},
    {"id": 251, "name": "ozersk",                    "city": "Озёрск"},
]

SERVERS = [
    {"name": "DC-01",          "ip": "172.16.16.2",  "role": "Domain Controller", "org": "luch"},
    {"name": "DC-02",          "ip": "172.16.16.3",  "role": "Domain Controller", "org": "luch"},
    {"name": "Exchange",       "ip": "172.16.16.10", "role": "Exchange 2019",      "org": "luch"},
    {"name": "ADFS",           "ip": "172.16.16.11", "role": "ADFS",               "org": "luch"},
    {"name": "UniFi",          "ip": "172.16.16.5",  "role": "UniFi Controller",   "org": "luch"},
    {"name": "Wazuh",          "ip": "172.16.16.100","role": "Wazuh SIEM",          "org": "luch"},
    {"name": "vCSA",           "ip": "172.16.16.20", "role": "VMware vCenter",     "org": "luch"},
    {"name": "nginx/PMG",      "ip": "10.69.69.250", "role": "Mail Gateway",       "org": "selectel"},
    {"name": "n8n",            "ip": "172.27.21.34", "role": "Automation",          "org": "luch"},
]
